### ISSUE TITLE
模拟器测试问题

### ISSUE THREAD

**Issue by iOSleep** [lingochamp/OnlineScorer-iOS#2]
demo工程在模拟器上crash在了`EZLog`上. 如下图: 
<img width="1400" alt="wx20170814-164221 2x" src="https://user-images.githubusercontent.com/26478957/29264421-95415d02-810f-11e7-9a7b-220e58f8c272.png">

**Comment by huajiahen** [comment]
是的，我最近发现了这个问题，在真机上不会发生这个问题，我正在想办法解决。如果急用的话，可以直接 NSLog -[NSString initWithFormat:argument:] 生成的 log 替换这一行。

**Comment by huajiahen** [comment]
0.0.3 已经 fix 这个问题了。有其他问题欢迎随时反馈~
