### ISSUE TITLE
默认使用speex问题

### ISSUE THREAD

**Issue by iOSleep** [lingochamp/OnlineScorer-iOS#3]
默认勾选了`user speex`, 录制完成后一直提示`receiving result`, 没有提示结果.
取消后, 可以拿到结果, 这是因为什么?

**Comment by huajiahen** [comment]
抱歉，这是一个 bug，我尽快解决后会在这里回复你。

**Comment by huajiahen** [comment]
0.0.3 已经 fix 这个问题了。有其他问题欢迎随时反馈~
