### ISSUE TITLE
关于停止录音的问题bug

### ISSUE THREAD

**Issue by OmgKevin** [lingochamp/OnlineScorer-iOS#5]
你好，我在用这个三方库的过程中遇到，当开始录音的时候，点击停止录音按钮，调用   
[_scorerRecorder stopRecording];这个方法，但是发现录音当前并没有停止而是继续录音状态，当我第二次再点击录音的时候，再点击停止才是正常的，请问可以告诉下是什么问题么

**Comment by huajiahen** [comment]
你好，在录音硬件启动完成前停止录音的调用会被忽略，以后可能会加上一些处理避免这种情况，目前还请在外部做保护禁止太短时间（推荐是1s)内停止录音

**Comment by OmgKevin** [comment]
我这边是OC版本写的，我在对比官网demo的时候，确实是发现这个问题的存在于OC版本，我可以拜托你你看一下我的demo嘛，发你邮箱

**Comment by huajiahen** [comment]
你是确定不是停止录音的操作太快导致的吗？你可以把你的项目放到Github上建个repo或者gist。

**Comment by OmgKevin** [comment]
嗯，我确定不是因为操作太快导致的问题 ，其实我就是在寻思[_scorerRecorder stopRecording];的外部时间保护是应该怎么样写？

**Comment by OmgKevin** [comment]
xingm78@163.com

**Comment by OmgKevin** [comment]
https://github.com/OmgKevin/RecordDemo ，你可以先看一下我上传的这快的录音相关的demo文件哈

**Comment by huajiahen** [comment]
你在 - [RecordViewController Scorer] 方法中结束录音马上又开始新的录音操作了，这是不可以的。新的录音必须在上一个录音完全结束后才可以进行，即回调 -[EZOnlineScorerRecorderDelegate  onlineScorerDidFinishRecording:] 或 -[EZOnlineScorerRecorderDelegate onlineScorer:didFailWithError:]后才允许新的录音。

**Comment by OmgKevin** [comment]
所以我要在停止播放的按钮方法里的 [_scorerRecorder stopRecording]; 方法下一步，添加调用 [self onlineScorerDidFinishRecording:_scorerRecorder]; 吗？

**Comment by huajiahen** [comment]
不是。这是回调的delegate方法，不是让你自己调用的，你需要等 Recorder 回调给你后再进行下一次录音。最简单的处理方案是你把录音和结束录音两件事分开，不要按一个按钮同时处理两件事情。

**Comment by OmgKevin** [comment]
你可以加一下我的QQ 1175523254 吗，我始终不能发现问题的所在

**Comment by huajiahen** [comment]
你的代码问题我没办法帮你，建议你直接使用demo项目。

**Comment by OmgKevin** [comment]
那请问原项目里有OC版的demo么

**Comment by huajiahen** [comment]
很抱歉，项目没有 Objective-C 版本的 demo，但里面没有涉及太多 swift 的特性，有基本的 CocoaTouch 框架开发知识应当是能看得懂的。
此外 OnlineScorer 项目是我们的商业项目，测试账号仅用于我们的客户预览功能使用，如有需要或更具体的技术支持请联系我们的销售团队。
